/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package storemanagementsystem;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;

/**
 *
 * @author Safdar
 */
public class SalesmanPrint extends javax.swing.JFrame {

    /**
     * Creates new form Print
     */
    Connection con1;
    PreparedStatement pst;
    ResultSet RS;
    
    public SalesmanPrint() {
        initComponents();
        
    }
    String TotalBil;
    String pay;
    String returnAmt;
    public SalesmanPrint(String sub, String pay, String reAmt, TableModel tablemodel) throws PrinterException {
        
        initComponents();
        this.TotalBil =sub;
        this.pay =pay;
        this.returnAmt =reAmt;
        jTextArea1.setText(jTextArea1.getText() +"----------------------------------------------------------------------------------\n");
        jTextArea1.setText(jTextArea1.getText() +"                        STORE MANAGEMENT SYSTEM BILL\n");
        jTextArea1.setText(jTextArea1.getText() +"----------------------------------------------------------------------------------\n");
        jTextArea1.setText(jTextArea1.getText() +"Product"+"\t"+"Price"+"\t"+"Quantity"+"\t"+"Total\n");
        for(int i= 0; i<tablemodel.getRowCount(); i++)
        {
            String Product = (String)tablemodel.getValueAt(i, 1);
            String Price = (String)tablemodel.getValueAt(i, 2);
            String Quantity = (String)tablemodel.getValueAt(i, 3);
            int total = (int)tablemodel.getValueAt(i, 4);
            jTextArea1.setText(jTextArea1.getText() +Product+"\t"+Price+"\t"+Quantity+"\t"+total+"\n");
            
            
            
            
            
            
        }
        jTextArea1.setText(jTextArea1.getText() +"----------------------------------------------------------------------------------\n");
        jTextArea1.setText(jTextArea1.getText() +"\n");       
        jTextArea1.setText(jTextArea1.getText() +"\t\tTotal Bill\n");
        jTextArea1.setText(jTextArea1.getText() +"\t\t"+sub+"\n");
        jTextArea1.setText(jTextArea1.getText() +"\t\tPay\n");
        jTextArea1.setText(jTextArea1.getText() +"\t\t"+pay+"\n");
        jTextArea1.setText(jTextArea1.getText() +"\t\tReturn Amount\n");
        jTextArea1.setText(jTextArea1.getText() +"\t\t"+reAmt+"\n");
        jTextArea1.setText(jTextArea1.getText() +"----------------------------------------------------------------------------------\n");
        jTextArea1.setText(jTextArea1.getText() +"Thank you for comming...");
        jTextArea1.print();
    }

//    Print(String totalBil, String pAy, String ReAmt, TableModel model) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseClicked
        // TODO add your handling code here:
        ShopeSalesman shp = new ShopeSalesman();
        this.hide();
        shp.setVisible(true);
    }//GEN-LAST:event_jTextArea1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesmanPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesmanPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesmanPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesmanPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesmanPrint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
